---
title: "Esercizi con Python"
output: html_notebook
---

Vari esercizi presi da Think in Python

## Python come calcolatrice

```{python}
import math
import numpy as np
```

1.  Il volume di una sfera di raggio **r** è $\frac{4}{3}\pi r^{3}$. Che volume ha una sfera di raggio 5?

```{python}
r = 5

def volumeSfera(raggio):
  volume = 4/3*math.pi*math.pow(raggio,3)
  print('Il volume di una sfera di raggio 5 è:',round(volume,2))

volumeSfera(r)
```

2.  Il prezzo di copertina di un libro è € 24,95, ma una libreria ottiene il 40% di sconto. I costi di spedizione sono € 3 per la prima copia e 75 centesimi per ogni copia aggiuntiva. Qual'è il costo totale di 60 copie?

```{python}
def costoTotale(prezzoCop,sconto,numCopie):
  prezzoScontato = prezzoCop - (sconto/100*prezzoCop)
  costiSpedizione = 0.75*np.ones(numCopie)
  costiSpedizione[0] = 3
  return(round(numCopie*prezzoScontato+sum(costiSpedizione),2))

print('60 copie del libro costano:',costoTotale(24.95,40,60),'€')
```

3.  Se uscite di casa alle 6:52 di mattina e correte 1 miglio a ritmo blando (8:15 al miglio), poi 3 miglia a ritmo moderato (7:12 al miglio), quindi 1 altro miglio a ritmo blando, a che ora tornate a casa per colazione?

```{python}
# Esco per correre alle 6:52
OraUscita = 6
minutiUscita = 52

TBl = (8*60)+15 # cadenza per miglio corsa blanda in secondi
TMo = (7*60)+12 # cadenza per miglio corsa moderata secondi
percorsoMg = [1,3,1] # 3 miglia Tbl + 1 miglio TMo + 1 miglio TBl

# Calcolo la Durata della corsa in secondi,Ore e minuti
TotSec = sum([percorsoMg[0]*TBl+percorsoMg[1]*TMo+percorsoMg[2]*TBl])
TotOre = math.floor(TotSec/3600)
TotMin = math.floor((TotSec%3600)/60)

# Aggiungo le ore e minuti alla partenza considerando che 60 minuti
# corrispondono ad un'ora (operatore % per calcolare il resto)
OraRientro = (OraUscita + TotOre)+math.floor((minutiUscita+TotMin)/60)
MinutoRientro = math.floor((minutiUscita+TotMin)%60)

# Stampo la soluzione
print('Sono uscito di casa per correre alle 6:52 e sono rientrato alle',OraRientro,':',MinutoRientro)
```

## Funzioni con python

1.  Scrivete una funzione chiamata **giustif_destra** che richieda una stringa **s** come parametro e stampi la stringa con tanti spazi iniziali da far sì che l'ultima lettera della stringa cada nella colonna 70 del display.

```{python}
# Ho aggiunto come ulteriore parametro anche il numero totale di colonne
# in questo modo verifico se funziona anche con numero minore di colonne
def giustif_destra(s,cols):
  if (len(s) < cols):
    print((cols-len(s))*' ',s)
  else:
    print(s)

# provo la funzione con parametri diversi
s = 'monty'
giustif_destra(s,60)
giustif_destra(s,4)
giustif_destra(s,30)
```

> Un oggetto funzione è un valore che potete assegnare a una variabile o passare come argomento. Ad esempio, **fai2volte** è una funzione che accetta un oggetto funzione come argomento e la chiama per due volte.

    def fai2volte (f):
      f()
      f()

> Ecco un esempio che usa **fai2volte** per chiamare una funzione di nome stampa_spam due volte.

    def stampa_spam():
      print('spam')

    fai2volte(stampa_spam)

1.  Scrivete questo esempio in uno script e provatelo.
2.  Modificate **fai2volte** in modo che accetti due argomenti, un oggetto funzione e un valore, e che chiami la funzione due volte passando il valore come argomento.
3.  Copiate nel vostro script la definizione di **stampa_2volte** che abbiamo visto nel corso di questo capitolo.
4.  Usate la versione modificata di **fai2volte** per chiamare **stampa_2volte** per due volte, passando 'spam' come argomento.
5.  Definite una nuova funzione di nome **fai_quattro** che richieda un oggetto funzione e un valore e chiami la funzione per 4 volte, passando il valore come argomento. Dovrebbero esserci solo due istruzioni nel corpo di questa funzione, non quattro.

```{python}

################Esercizio 1#######################
# definisco la funzione stampa spam
def stampa_spam():
  print('spam')

# definisco la funzione fai due volte
def fai2volte (f):
  f()
  f()

# faccio il test della funzione fai due volte
fai2volte(stampa_spam)

################Esercizio 2#######################
# creo la funzione che stampa il valore
def stampa_val(val):
  print(val)

# modifico la funzione fai2volte per aggiungere un argomento valore
def fai2volte(f,val):
  f(val)
  f(val)

# Provo la funzione
fai2volte(stampa_val,'prova')
```
